from sqlmodel import SQLModel, Field

# this will automatically generate a class name for a table by default
# so class name is User so the table name also will be User

class User(SQLModel , table=True):

    # using table name will override and create a table named user
    __tablename__ = 'user'

    # id is auto-generated by MySQL (auto increment) for each user
    # default=None means we don't pass id when creating a User, the database creates it automatically
    id: int | None = Field(default=None, primary_key=True)
    first_name: str = Field(max_length=50)
    last_name: str = Field(max_length=50)
    email: str = Field(max_length=70, unique=True)
    password: str = Field(max_length=150)